// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5wHotWMzJ9kiN4InYIdpx4UuQCEVJw4Q',
    appId: '1:657400963470:web:c8f5271128cb976c2204df',
    messagingSenderId: '657400963470',
    projectId: 'smarttodolist-a9182',
    authDomain: 'smarttodolist-a9182.firebaseapp.com',
    storageBucket: 'smarttodolist-a9182.firebasestorage.app',
    measurementId: 'G-RD4Y354X2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy_slOGxzPqQ-Q754eA95-yCjqWB-EQnc',
    appId: '1:657400963470:android:240304fd0e2911072204df',
    messagingSenderId: '657400963470',
    projectId: 'smarttodolist-a9182',
    storageBucket: 'smarttodolist-a9182.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM-fUAuipnWjE7ePG2tz6hz41k5vG-8lU',
    appId: '1:657400963470:ios:34aac89e11d88c182204df',
    messagingSenderId: '657400963470',
    projectId: 'smarttodolist-a9182',
    storageBucket: 'smarttodolist-a9182.firebasestorage.app',
    iosBundleId: 'com.example.smartTodoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5wHotWMzJ9kiN4InYIdpx4UuQCEVJw4Q',
    appId: '1:657400963470:web:e78b339cf6fec5932204df',
    messagingSenderId: '657400963470',
    projectId: 'smarttodolist-a9182',
    authDomain: 'smarttodolist-a9182.firebaseapp.com',
    storageBucket: 'smarttodolist-a9182.firebasestorage.app',
    measurementId: 'G-C9QFVE7SF3',
  );
}
